### ISSUE TITLE
Fatal from sg-cachepress running slog admin > driver 

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/slog#29]
When changing settings on slog admin > driver I get warning messages from sg-cachepress. 
These occur with the latest version of SiteGround Optimizer, the sg-cachepress plugin .

Warning: Use of undefined constant COOKIEHASH - assumed 'COOKIEHASH' (this will throw an Error in a future version of PHP) in /home/customer/www/bobbingwide.com/public_html/wp-content/plugins/sg-cachepress/core/File_Cacher/File_Cacher.php on line 785

Warning: Cannot modify header information - headers already sent by (output started at /home/customer/www/bobbingwide.com/public_html/wp-content/plugins/sg-cachepress/core/File_Cacher/File_Cacher.php:785) in /home/customer/www/bobbingwide.com/public_html/wp-admin/includes/misc.php on line 1416

**Comment by bobbingwide** [comment]
The problem occurs when File-Based Caching is turned on.

**Comment by bobbingwide** [comment]
`COOKIEHASH` is defined in `wp_cookie_constants()`

**Comment by bobbingwide** [comment]
I recreated the problem in a local WPMS network ( `sb/wp55` ). It produced a Fatal error in PHP 8.
<b>Fatal error</b>:  Uncaught Error: Undefined constant &quot;SiteGround_Optimizer\File_Cacher\COOKIEHASH&quot; in C:\apache\htdocs\wp55\wp-content\plugins\sg-cachepress\core\File_Cacher\File_Cacher.php:785
Stack trace:
```
#0 C:\apache\htdocs\wp55\wp-content\plugins\sg-cachepress\core\File_Cacher\File_Cacher.php(817): SiteGround_Optimizer\File_Cacher\File_Cacher-&gt;create_config()
#1 C:\apache\htdocs\wp55\wp-content\plugins\sg-cachepress\core\File_Cacher\File_Cacher.php(555): SiteGround_Optimizer\File_Cacher\File_Cacher-&gt;refresh_config()
#2 C:\apache\htdocs\wp55\wp-content\plugins\sg-cachepress\core\Supercacher\Supercacher.php(302): SiteGround_Optimizer\File_Cacher\File_Cacher-&gt;purge_everything()
#3 C:\apache\htdocs\wp55\wp-content\plugins\sg-cachepress\core\Loader\Loader.php(685): SiteGround_Optimizer\Supercacher\Supercacher-&gt;purge_on_options_save()
#4 C:\apache\htdocs\wp55\wp-content\plugins\sg-cachepress\core\Loader\Loader.php(667): SiteGround_Optimizer\Loader\Loader-&gt;add_caching_hooks(Object(SiteGround_Optimizer\File_Cacher\File_Cacher))
#5 [internal function]: SiteGround_Optimizer\Loader\Loader-&gt;add_file_cacher_hooks()
#6 C:\apache\htdocs\wp55\wp-content\plugins\sg-cachepress\core\Loader\Loader.php(195): call_user_func(Array)
#7 C:\apache\htdocs\wp55\wp-content\plugins\sg-cachepress\core\Loader\Loader.php(82): SiteGround_Optimizer\Loader\Loader-&gt;add_hooks()
#8 C:\apache\htdocs\wp55\wp-content\plugins\sg-cachepress\sg-cachepress.php(72): SiteGround_Optimizer\Loader\Loader-&gt;__construct()
#9 C:\apache\htdocs\wp55\wp-settings.php(392): include_once('C:\\apache\\htdoc...')
#10 C:\apache\htdocs\wp55\wp-config.php(113): require_once('C:\\apache\\htdoc...')
#11 C:\apache\htdocs\wp55\wp-load.php(50): require_once('C:\\apache\\htdoc...')
#12 C:\apache\htdocs\wp55\wp-admin\admin.php(34): require_once('C:\\apache\\htdoc...')
#13 C:\apache\htdocs\wp55\wp-admin\options.php(19): require_once('C:\\apache\\htdoc...')
#14 {main}
  thrown in <b>C:\apache\htdocs\wp55\wp-content\plugins\sg-cachepress\core\File_Cacher\File_Cacher.php</b> on line <b>785</b><br />
```

**Comment by bobbingwide** [comment]
The problem occurs because COOKIEHASH has not yet been defined. I resolved this issue locally by adding a call to `wp_cookie_constants()` before creating the `$config` array and prefixing `COOKIEHASH` with a backslash, for the namespace issue.

**Comment by bobbingwide** [comment]
I raised a new support topic 
https://wordpress.org/support/topic/fatal-undefined-constant-siteground_optimizerfile_cachercookiehash/

The original problem is 

https://wordpress.org/support/topic/warning-use-of-undefined-constant-cookiehash/

**Comment by bobbingwide** [comment]
SiteGround have replied to the new support topic, by saying it’s been forwarded to the development team. They’ve closed the entry as resolved, which is extremely premature in my opinion.
